"""
Universal Observatory Operating System
Shared constants v0.1
"""

UNKNOWN = "unknown"
OBSERVED = "observed"
ARCHIVED = "archived"
RECORDED = "recorded"

OBJECT_CREATED = "OBJECT_CREATED"
OBJECT_UPDATED = "OBJECT_UPDATED"
RELATIONSHIP_CREATED = "RELATIONSHIP_CREATED"

OBSERVES = "OBSERVES"
DETECTS = "DETECTS"
MEASURES = "MEASURES"
SUPPORTS = "SUPPORTS"
CONTRADICTS = "CONTRADICTS"
RELATED_TO = "RELATED_TO"

DEFAULT_VERSION = "0.1"
MANUAL_ENTRY = "manual_entry"